[build]
builder = "NIXPACKS"
buildCommand = "npm install && VITE_API_URL=$VITE_API_URL npm run build"

[deploy]
startCommand = "npx serve dist -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
